### ISSUE TITLE
[ENHANCEMENT] Avatar Search / Unlimited Favourites / Favourite Private Worlds

### ISSUE THREAD

**Issue by Grobitalks** [autumncpp/void-issues#4]
A Void avatar search would be cool since everything else kinda sucks. Same goes for the unlimited favourites and the world saving

Emm has spaghetti code plus has lots of useless features that other mods do better (same goes for remod.)

**Comment by Azurilex** [comment]
This has been suggested a lot and I'm keeping it in mind. I wouldn't necessarily say it's high on my priority list though. It's unlikely that I'll implement avatar searching, but unlimited favorites is something I'll get to when the time is right. This will stay open until it's implemented so that it doesn't get suggested again.
